sonar.projectKey=xhrobj-hex_go-project-244
sonar.organization=xhrobj-hex

sonar.sources=.
sonar.tests=.
sonar.exclusions=**/*_test.go,**/testdata/**
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
