sonar.projectKey=xhrobj-hex_go-project-244
sonar.organization=xhrobj-hex

sonar.sources=.
sonar.tests=.

sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/testdata/**

sonar.go.coverage.reportPaths=coverage.out

sonar.issue.ignore.multicriteria=ignoreTests
sonar.issue.ignore.multicriteria.ignoreTests.ruleKey=*
sonar.issue.ignore.multicriteria.ignoreTests.resourceKey=**/*_test.go
