name: (-_-) go-ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
    
      - name: (^_^) Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
      
      - name: (^_^) Run tests with coverage for SonarQube
        run: make test-with-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
